site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/
use_directory_urls: true
theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.trackbig
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - toc.integrate  
    - header.autohide  
    - logo: images/favicon.ico
extra_javascript:
    - javascripts/highlight.min.js
plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter  
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - codehilite
  - fenced_code
  - tables
  - sane_lists
repo_url: https://github.com/vscosta/yap


