site_name: YAP Prolog Reference Manual
use_directory_urls: true
theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.trackibg
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - toc.integrate  
    - header.autohide  
    - favicon: docs/img/icons/favicon.ico
plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter  
markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
  - admonition
  - codehilite
  - fenced_code
  - tables
  - sane_lists


