site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/
use_directory_urls: true
theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.trackbig
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - toc.integrate  
    - header.autohide  
    - logo: favicon.ico
    - content.tooltips
extra_javascript:
    - javascripts/highlight.min.js
plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter  
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - codehilite
  - fenced_code
  - toc:
      permalink: true
nav:
   - Home: page-index.md
   - INSTALL: page-INSTALL.md
   - run: page-run.md
   - Core Built-ins: page-Builtins.md
   - load_files:
       - page-load_files.md
       - modules: page-modules.md
   - programming:
      - page-programming.md
      - syntax: page-syntax.md
      - swi: page-swi.md
   - Extensions:
      - page-YapExtensions.md
      - Attributes: page-AttributedVariables.md
   - Library: page-YAPLibrary.md
   - packages: page-packages.md
   - Foreign Language Interface : page-fli_c_xx.md
