site_name: YAP Prolog Reference Manual
theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - toc.integrate  
    - header.autohide  
    - favicon: images/favicon.png
plugins:
  - search
  - mkdocs-jupyter  
markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
  - admonition
  - codehilite
  - fenced_code
  - tables
  - sane_lists
nav:
  - Home: /yap/doxybook2/
  - Modules:  /yap/doxybook2/Groups
  - Classes:  /yap/doxybook2/Classes
  - Namespaces:  /yap/doxybook2/Namespaces
  - Files:  /yap/doxybook2/Files
  - Related Pages:  /yap/doxybook2/Pages
  - Examples:  /yap/doxybook2/Examples

